import sqlite3

target_conn = sqlite3.connect('data/target.db')
target_cur = target_conn.cursor()

source_conn = sqlite3.connect('data/source.db')
source_cur = source_conn.cursor()

target_cur.execute("DROP TABLE IF EXISTS customers")
target_cur.execute("DROP TABLE IF EXISTS orders")
target_cur.execute("DROP TABLE IF EXISTS products")
target_cur.execute("DROP TABLE IF EXISTS order_items")
target_cur.execute("DROP TABLE IF EXISTS payments")
target_cur.execute("DROP TABLE IF EXISTS returns")
target_cur.execute("DROP TABLE IF EXISTS departments")
target_cur.execute("DROP TABLE IF EXISTS employees")
target_cur.execute("DROP TABLE IF EXISTS projects")
target_cur.execute("DROP TABLE IF EXISTS tasks")
target_cur.execute("DROP TABLE IF EXISTS salaries")
target_cur.execute("DROP TABLE IF EXISTS attendance")
target_cur.execute("DROP TABLE IF EXISTS leaves")
target_cur.execute("DROP TABLE IF EXISTS clients")
target_cur.execute("DROP TABLE IF EXISTS meetings")
target_cur.execute("DROP TABLE IF EXISTS assets")
target_cur.execute("DROP TABLE IF EXISTS training")
target_cur.execute("DROP TABLE IF EXISTS audit_logs")
